[package]
name = "apns2"
version = "0.0.1"
authors = ["Sergey Tkachenko <seriy.tkachenko@gmail.com>"]
license = "MIT"
readme  = "README.md"
description = "HTTP/2 Apple Push Notification Service for Rust"
keywords    = ["apns", "apple", "push", "notification", "http2", "http/2"]
repository  = "https://github.com/tkabit/apns2.git"
homepage    = "https://github.com/tkabit/apns2"
documentation = "https://github.com/tkabit/apns2"

[dependencies]
rustc-serialize = "~0.3"
time = "~0.1"

[dependencies.openssl]
version = "~0.7"
features = ["tlsv1_2", "npn", "alpn"]

[dependencies.solicit]
git = "https://github.com/pimeys/solicit"
default-features = true
features = ["tls"]

[dependencies.openssl]
default-features = true
features = ["alpn"]
version = "~0.6"
