[package]
name = "apns2"
version = "0.0.1"
authors = ["Sergey Tkachenko <seriy.tkachenko@gmail.com>"]
license = "MIT"
description = "HTTP/2 Apple Push Notification Service for Rust"
repository = "https://github.com/tkabit/apns2"

[dependencies]
hyper = "~0.7"
rustc-serialize = "~0.3"
